### ISSUE TITLE
Query: move styling in components to /css and /scss?

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#3]
This is a minor issue if it's one at all. 

I'm sure there's a good reason for it, but the following files contain CSS:

```
src/bq-components/bq-param-paginator.scss
src/bq-components/bq-paginator.scss
public/components/bq-components.all.html
public/components/bq-paginator.html
public/components/bq-paginator.html
```

Could/should these rules be moved to suitable places in `src/scss` and `public/css`, so that their styling rules don't cause confusion with future stylesheeting work? Or do they need to be kept with their components?

**Comment by craigmj** [comment]
The items in the components are ONLY used in the Admin. So we don't want 
them mixed with the regular styling that appears for the standard site. 
Also, because they're used in the admin, they're actually part of the 
webcomponents that do various things in the admin (largely paginator). 
Webcomponents is an emerging standard, and the css needs to stay with 
the components - in fact, it doesn't mix with the other css on the page, 
and is encapsulated in something called the 'shadow dom' with various 
levels of success (because there's not yet agreement over the 'standard').

Because of the way webcomponents and shadow-dom work, there's no risk of 
them overlapping with other styling (or there _should be_ no risk, lol, 
depending on how the webcomponent implementation pans out in the browser).

All the best,
C

**Comment by arthurattwell** [comment]
Perfect. Webcomponents in the wild! Till now I'd only read about them :) Thanks.

**Comment by craigmj** [comment]
We've been using them for a while on Admin sides of sites. They work 
nicely in Chrome and Firefox (although sometimes there are issues with 
compatibility). It seems like a promising technology, although there are 
still lots of unresolved technical issues that might stymie them going 
forward. But for Admin sites, where we can (sort of) specify the browser 
to use, they are pretty nice to use.

C
